name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Target Device'
        required: true
        default: 'a32'
        type: choice
        options:
          - a32
          - a22
          - f22
          - m22
          - m32

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache flex g++-multilib gcc-multilib git gnupg gperf lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 libncurses5-dev curl
          sudo ln -s /usr/lib/x86_64-linux-gnu/libxml2.so.2 /usr/lib/x86_64-linux-gnu/libxml2.so.16 2>/dev/null || true

      - name: Download Clang Toolchain
        run: |
          mkdir -p clang
          cd clang
          curl -LO https://github.com/kdrag0n/proton-clang/archive/refs/heads/master.tar.gz
          tar -xf master.tar.gz --strip-components=1
          rm master.tar.gz

      - name: Build Kernel
        env:
          DEVICE: ${{ github.event.inputs.device }}
          ARCH: arm64
          KCFLAGS: ' -w -pipe -O3'
          KCPPFLAGS: ' -O3'
          CONFIG_SECTION_MISMATCH_WARN_ONLY: y
        run: |
          export PATH="$(pwd)/clang/bin:$PATH"
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          export LD=ld.lld
          export OBJCOPY=llvm-objcopy
          export AS=llvm-as
          export NM=llvm-nm
          export STRIP=llvm-strip
          export OBJDUMP=llvm-objdump
          export READELF=llvm-readelf
          export CC=clang
          
          CFGDIR=arch/arm64/configs
          rm -rf $CFGDIR/compiled_defconfig
          
          make -C $(pwd) O=$(pwd)/out clean -j$(nproc)
          make -C $(pwd) O=$(pwd)/out mrproper -j$(nproc)
          
          cat $CFGDIR/mt6768_slm_defconfig $CFGDIR/$DEVICE.config $CFGDIR/battery.config > $CFGDIR/compiled_defconfig
          
          # Жестко отключаем BTF отладку и генерацию через pahole
          echo '
          CONFIG_ALWAYS_PERMISSIVE=y
          CONFIG_MTK_GPU_VERSION="mali valhall r32p1"
          # CONFIG_DEBUG_INFO_BTF is not set
          CONFIG_DEBUG_INFO_BTF=n
          # CONFIG_DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT is not set
          CONFIG_DEBUG_INFO_REDUCED=y
          ' >> "$CFGDIR/compiled_defconfig"
          
          make -C $(pwd) O=$(pwd)/out -j$(nproc) compiled_defconfig
          make -s -C $(pwd) O=$(pwd)/out -j$(nproc)

      - name: Verify and Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Image-${{ github.event.inputs.device }}
          path: out/arch/arm64/boot/Image
