name: Upstream Merge 4.14.364 (wip)

on:
  workflow_dispatch: 

jobs:
  merge-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: wip  # Указываем, что работаем именно с веткой wip

      - name: Configure Git
        run: |
          git config user.name "AutoMergeBot"
          git config user.email "bot@example.com"
          git remote add stable git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git

      - name: Fetch and Merge
        run: |
          git fetch --depth 1 stable tag v4.14.364
          # Делаем мердж, если возникнут конфликты, скрипт остановится с ошибкой
          git merge v4.14.364 --no-edit

      - name: Push changes
        run: |
          # Пушим результат обратно в ветку wip
          git push origin wip
          
